### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [bortels/HersheyCodea#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by bortels** [comment]
No - this project is simply re-encoding an existing Hershey font to a format suitable for Codea, and had nothing to do with introducing new fonts to the Hershey family. The Hershey font format is very old and simple, and so was easy to adopt. I suspect most modern fonts would be difficult to convert, but for Codea at least they should already be built-in to the software.

**Comment by mkeyno** [comment]
do you know any method for converting a font to the vector type ?
